FROM python:latest

WORKDIR /usr/src/app

# Install Django
RUN apt update && apt upgrade -y
RUN python -m pip install Django

COPY ./runserver.sh /usr/bin/

# Install project dependencies
RUN pip install django djangorestframework
RUN pip install django psycopg2
RUN pip install django-cors-headers
RUN pip install Pillow
RUN pip install django-oauth-toolkit

EXPOSE 8080

CMD [ "/usr/bin/runserver.sh" ]

